/**
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param enumFormStringArray Form parameter enum test (string array)
 * @param enumFormString Form parameter enum test (string)
 * @param enumQueryDouble Query parameter enum test (double)
 */
case class EnumFormBody (
  enumFormStringArray: Option[EnumFormBody.List[EnumFormStringArray]] = None,
  enumFormString: Option[EnumFormBody.EnumFormString] = None,
  enumQueryDouble: Option[EnumFormBody.EnumQueryDouble] = None
)

object EnumFormBody {
  type List[EnumFormStringArray] = List[EnumFormStringArray].Value
  type EnumFormString = EnumFormString.Value
  type EnumQueryDouble = EnumQueryDouble.Value

  object List[EnumFormStringArray] extends Enumeration {
  }

  object EnumFormString extends Enumeration {
    val Abc = Value("_abc")
    val Efg = Value("-efg")
    val Xyz = Value("(xyz)")
  }

  object EnumQueryDouble extends Enumeration {
    val `11` = Value("1.1")
    val `12` = Value("-1.2")
  }

}
