/**
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param enumString 
 * @param enumInteger 
 * @param enumNumber 
 * @param outerEnum 
 */
case class EnumTest (
  enumString: Option[EnumTest.EnumString] = None,
  enumInteger: Option[EnumTest.EnumInteger] = None,
  enumNumber: Option[EnumTest.EnumNumber] = None,
  outerEnum: Option[OuterEnum] = None
)

object EnumTest {
  type EnumString = EnumString.Value
  type EnumInteger = EnumInteger.Value
  type EnumNumber = EnumNumber.Value

  object EnumString extends Enumeration {
    val UPPER = Value("UPPER")
    val Lower = Value("lower")
    val `` = Value("")
  }

  object EnumInteger extends Enumeration {
    val `1` = Value("1")
    val `1` = Value("-1")
  }

  object EnumNumber extends Enumeration {
    val `11` = Value("1.1")
    val `12` = Value("-1.2")
  }

}
